name: Maven Build and Trigger Jenkins

on:
  push:
    branches:
      - main  # Run workflow on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify the Java distribution (e.g., temurin, zulu)
          java-version: '11'       # Specify the Java version you want to use

      # Step 3: Build the site
      - name: Build static site
        run: mvn clean site

  trigger-jenkins:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Jenkins Crumb
        id: crumb
        run: |
          response=$(curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
          "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json")
          echo "crumb=$(echo $response | jq -r .crumb)" >> $GITHUB_ENV
          
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/deploystaticweb/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
          -H "Jenkins-Crumb: ${{ secrets.crumb }}" \
          --data-urlencode "GITHUB_COMMIT_SHA=${{ github.sha }}" \
          --data-urlencode "BRANCH_NAME=${{ github.ref_name }}" \
<<<<<<< HEAD
          --data-urlencode "BUILD_SOURCE=GitHub Actions"
=======
<<<<<<< HEAD
          --data-urlencode "BUILD_SOURCE=GitHub Actions"
=======
          --data-urlencode "BUILD_SOURCE=GitHub Actions"

