name: Maven Build

on:
  push:
    branches:
      - main  # Run workflow on pushes to the 'main' branch
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify the Java distribution (e.g., temurin, zulu)
          java-version: '11'       # Specify the Java version you want to use

      # Step 3: Build the site
      - name: Build static site
        run: mvn clean site
